### ISSUE TITLE
UAVCAN index usage in conversion

### ISSUE THREAD

**Issue by zerodamage** [SubC-Partner/uavcan_ros_bridge#2]
https://github.com/SubC-Partner/uavcan_ros_bridge/blob/714dfefd100f4f4d5b041d20cd10eee103383ee8/uavcan_ros_bridge/src/ros_to_uav/rpm_command.cpp#L17

**Comment by zerodamage** [comment]
@jbrsc Det et array index [0] der styre hvilke ESC der adresseres jævnfør 
https://docs.px4.io/main/en/peripherals/vesc.html

**Comment by jbrsc** [comment]
Er det den der hedder array command i ros_uavcan_bridge.cpp eller er det en
fil jeg finder i libuav eller dsdl?

tor. 19. okt. 2023 17.28 skrev Christian Mai ***@***.***>:

**Comment by zerodamage** [comment]
Det er RPMCommand, som også bruges nu, det er blot at det rent faktisk er et array, som skal udfyldes.

Lige nu udfylder vi kun index 0, men alle 0...9 skal udfyldes for at nå alle motorerne.

Der skal ikke som udgangspunkt laves noget i dsdl.

Se den linie jeg har linket i issue.

Best Regards/Venlig Hilsen
Christian Mai

________________________________

**Comment by zerodamage** [comment]
@jbrsc har tilføjet et par kommentarer i rpm_command.cpp som viser princippet

**Comment by jbrsc** [comment]
@zerodamage Det virker, jeg pusher den lige så du kan se hvordan, det er blevet sat op.

Det var faktisk en af de første parametrer som jeg ændrede på i mandags, (da vesc stadig havde ids 106 107 osv) så jeg fik aldrig noget ud af at ændre på hverken array size eller array nummer.
Men det var før at jeg havde læst alt dokumentationen, allerede om tirsdagen havde jeg ændret til 0-9 men der havde jeg så stadigvæk afsat værdien som værene ubetydelig, også især fordi at jeg der troede de 106 og 107 der blev skrevet i ros_uavcan_bridge filen havde en anden betydning end bare en id værdi.

Jeg har tilføjet en unsigend char til converteren som modtager de specifikke ids, og sat dem op i if statements, ellers ville alle thrustere køre
